<a href="https://colab.research.google.com/github/asadmobashshir/asadmobashshir/blob/main/Artificial_Neural_Network_(Regression).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [ ]:
tf.__version__

'2.19.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset=pd.read_excel('Folds5x2_pp.xlsx')
X=dataset.iloc[:, :-1].values
y=dataset.iloc[:, -1].values

In [ ]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer='adam', loss='mean_squared_error')

### Training the ANN model on the Training set

In [ ]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 486210.0000
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 86521.4766 
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6406.0688 
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 313.7563
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 283.8742
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 281.7647
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 279.5031
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 276.6881
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 273.7317
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 270.5100
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 266.4482
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 262.0940
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 257.2091
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 251.8455
Epoch 1

### Predicting the results of the Test set

In [ ]:
y_pred=ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)), 1))

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[430.95 431.23]
 [462.1  460.01]
 [465.67 461.14]
 ...
 [472.8  473.26]
 [439.74 438.  ]
 [458.89 463.28]]
